//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FX.Core.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FX.Core.Common.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array.
        /// </summary>
        public static string Array {
            get {
                return ResourceManager.GetString("Array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access the requested path.
        /// </summary>
        public static string CannotAccessTheRequestedPath {
            get {
                return ResourceManager.GetString("CannotAccessTheRequestedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be null or empty.
        /// </summary>
        public static string CannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("CannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert data into the specified type.
        /// </summary>
        public static string CannotConvertToTheSpecifiedType {
            get {
                return ResourceManager.GetString("CannotConvertToTheSpecifiedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File cannot be copied.
        /// </summary>
        public static string FileCannotBeCopied {
            get {
                return ResourceManager.GetString("FileCannotBeCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist.
        /// </summary>
        public static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid column count.
        /// </summary>
        public static string InvalidColumnCount {
            get {
                return ResourceManager.GetString("InvalidColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length is greater than.
        /// </summary>
        public static string LengthIsGreaterThan {
            get {
                return ResourceManager.GetString("LengthIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length is less than.
        /// </summary>
        public static string LengthIsLessThan {
            get {
                return ResourceManager.GetString("LengthIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length is not equal to.
        /// </summary>
        public static string LengthIsNotEqualTo {
            get {
                return ResourceManager.GetString("LengthIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid double number.
        /// </summary>
        public static string MustBeAValidDoubleNumber {
            get {
                return ResourceManager.GetString("MustBeAValidDoubleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid positive long number.
        /// </summary>
        public static string MustBeAValidPositiveLongNumber {
            get {
                return ResourceManager.GetString("MustBeAValidPositiveLongNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be in range.
        /// </summary>
        public static string MustBeInRange {
            get {
                return ResourceManager.GetString("MustBeInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be specified.
        /// </summary>
        public static string MustBeSpecified {
            get {
                return ResourceManager.GetString("MustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file specified.
        /// </summary>
        public static string NoFileSpecified {
            get {
                return ResourceManager.GetString("NoFileSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown file type.
        /// </summary>
        public static string UnknownFileType {
            get {
                return ResourceManager.GetString("UnknownFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
